### ISSUE TITLE
'NoneType' object has no attribute 'replace' - Big PSQL Dedupe Example

### ISSUE THREAD

**Issue by primoz-k** [datamade/dedupe-examples#29]
Running `pgsql_big_dedupe_example.py` in Python 2.7 environment fails:

    Finished labeling
    blocking...
    creating blocking_map database
    creating inverted index
    Traceback (most recent call last):
        File "pgsql_big_dedupe_example.py", line 194, in <module>
           deduper.blocker.index(field_data, field)
        File "/home/pk6730/.virtualenvs/dedupe_examples/local/lib/python2.7/site-packages/dedupe/blocking.py", line 74, in index
           index.index(preprocess(doc))
        File "/home/pk6730/.virtualenvs/dedupe_examples/local/lib/python2.7/site-packages/dedupe/predicates.py", line 161, in preprocess
           return tuple(ngrams(doc.replace(' ', ''), 2))
    AttributeError: 'NoneType' object has no attribute 'replace'

Did not encounter this error in my other 3.4 env.

**Comment by fgregg** [comment]
Closed by https://github.com/datamade/dedupe/commit/b8e00e9d02330f0c37b9a59c44576bcb8ca5b8c6
