### ISSUE TITLE
Error running mysql_example: "Incorrect datetime value: ' ' for function str_to_date

### ISSUE THREAD

**Issue by LokeshRishi** [datamade/dedupe-examples#40]
I am getting the following error while trying to run _mysql example_:

> downloading Illinois-campaign-contributions.txt.zip (~60mb) ...
> extracting Illinois-campaign-contributions.txt.zip
> importing raw data from csv...
> creating donors table...
> creating indexes on donors table
> creating recipients table...
> creating contributions table
> Traceback (most recent call last):

>   File "mysql_db_init.py", line 141, in <module>
>     c.execute("INSERT INTO contributions "

>   File "/usr/lib/python2.7/dist-packages/MySQLdb/cursors.py", line 226, in execute
>     self.errorhandler(self, exc, value)

>   File "/usr/lib/python2.7/dist-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
>     raise errorvalue

> _mysql_exceptions.OperationalError: (1411, "Incorrect datetime value: ' ' for function str_to_date")
>

**Comment by LokeshRishi** [comment]
Resolved by enabling the _ALLOW_INVALID_DATES_ SQL mode.
